# Generated by Django 3.2.6 on 2021-11-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice_lines',
        ),
        migrations.DeleteModel(
            name='Invoices',
        ),
    ]
