# Generated by Django 3.2.6 on 2021-11-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20211108_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice_lines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField(default=0)),
                ('course_id', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('teacher_id', models.IntegerField(default=0)),
                ('purchase_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='invoices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_id', models.IntegerField(default=0)),
                ('course_id', models.IntegerField(default=0)),
                ('request_date', models.DateField()),
            ],
        ),
    ]
