# Generated by Django 3.2.6 on 2021-11-24 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_testvideo_vimeo_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice_lines',
        ),
        migrations.DeleteModel(
            name='Invoices',
        ),
    ]
