# Generated by Django 3.2.9 on 2021-11-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20211122_1718'),
    ]

    operations = [

    ]
